development:
  adapter: mysql2
  encoding: utf8
  database: actioncable-react_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: actioncable-react_test
  pool: 5
  username: root
  password:
